### ISSUE TITLE
Fix hooks and card automation

### ISSUE THREAD

**Issue by glasnt** [glasnt/blog#1]
At some point I had this working but really didn't document it. 

The pre-commit hook was

```
/Users/glasnt/git/glasnt/blog/venv/bin/python assets/card_helpers/generate.py --quiet
```
And this was committed into the .github/hooks/ directory which might have been actually picked up by github and had that weird "you have to commit twice for new posts to turn up" bug I was getting. 

Now, even on the machine I created it on, I get:

```
Traceback (most recent call last):
  File "assets/card_helpers/generate.py", line 68, in <module>
    main()
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "assets/card_helpers/generate.py", line 59, in main
    resp = process(post, png)
  File "assets/card_helpers/generate.py", line 38, in process
    img = imgkit.from_string(render, png, options={"width": WIDTH, "quiet": ""})
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/imgkit/api.py", line 90, in from_string
    return rtn.to_img(output_path)
  File "/Users/glasnt/git/glasnt/blog/venv/lib/python3.8/site-packages/imgkit/imgkit.py", line 240, in to_img
    raise IOError('wkhtmltoimage reported an error:\n' + stderr)
OSError: wkhtmltoimage reported an error:
Exit with code 1 due to network error: ProtocolUnknownError
```

I have no idea what I was doing, and the current README.md was for the service that this was going to be, until I realised this is a static site so I should generate images statically instead of dynamically. 

I was too clever and now current Katie is dealing with the mess.

**Comment by glasnt** [comment]
This was resolved in some earlier commit that I don't remember, but there's docs now.
